# Generated by Django 3.2.8 on 2021-12-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='date',
            field=models.DateField(),
        ),
    ]
