# Generated by Django 3.2.8 on 2021-12-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsint',
            name='internship',
        ),
        migrations.AddField(
            model_name='applicationsint',
            name='circulumvitae',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
