# Generated by Django 3.2.8 on 2021-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0002_alter_internships_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
