# Generated by Django 3.2.8 on 2021-12-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagecomfacade', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Internships_images')),
                ('level', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=255)),
                ('requirements', models.TextField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
