# Generated by Django 3.2.8 on 2021-12-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0002_auto_20211215_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='deadline',
            field=models.DateField(),
        ),
    ]
