# Generated by Django 3.2.8 on 2021-12-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0002_auto_20211214_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsint',
            name='internship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stagecomfacade.internships'),
            preserve_default=False,
        ),
    ]
