# Generated by Django 3.2.8 on 2021-12-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0003_internships'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
