# Generated by Django 4.0.3 on 2022-06-01 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagecomfacade', '0003_internships_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Courses_images')),
                ('level', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=255)),
                ('requirements', models.TextField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('rate', models.IntegerField(default=2, max_length=1)),
                ('price', models.FloatField(default=0)),
                ('duration', models.TimeField(max_length=5)),
                ('peopleenrolled', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='text',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
