# Generated by Django 3.2.8 on 2021-12-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0003_applicationsint_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsint',
            name='internship',
        ),
    ]
