# Generated by Django 3.2.8 on 2021-12-14 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagecomfacade', '0004_remove_applicationsint_internship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationsInt',
        ),
        migrations.AlterField(
            model_name='internshipsapplicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
