# Generated by Django 3.2.8 on 2021-12-10 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagecomfacade', '0005_wishinternship'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipsApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulumvitae', models.FileField(upload_to='cv internships')),
                ('motivationLetter', models.TextField()),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagecomfacade.internships')),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
