# Generated by Django 3.2.8 on 2021-12-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0006_internshipsapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipsapplicant',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
