# Generated by Django 3.2.8 on 2021-12-10 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagecomfacade', '0007_internshipsapplicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipsapplicant',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipsapplicant',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
