# Generated by Django 3.2.8 on 2021-12-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0008_auto_20211210_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipsapplicant',
            name='circulumvitae',
            field=models.FileField(blank=True, upload_to='cv internships'),
        ),
    ]
