# Generated by Django 3.2.8 on 2021-12-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagecomfacade', '0009_alter_internshipsapplicant_circulumvitae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='blog_images')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=60)),
            ],
        ),
    ]
