# Generated by Django 3.2.8 on 2021-12-13 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagecomfacade', '0012_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipsapplicant',
            name='circulumvitae',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='applicationsInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('motivationLetter', models.TextField()),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagecomfacade.internships')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
